In [1]:
import numpy as np
from scipy.stats import chi2_contingency

# Masukkan data tabel sesuai soal
data = np.array([
    [14, 6, 9],
    [10, 16, 10],
    [2, 13, 20]
])

# Uji chi-square
chi2, p, dof, expected = chi2_contingency(data)

print("Chi-square hitung:", round(chi2, 5))
print("df:", dof)
print("p-value:", p)
print("Tabel expected:")
print(np.round(expected, 2))

Chi-square hitung: 18.36653
df: 4
p-value: 0.001046273329595159
Tabel expected:
[[ 7.54 10.15 11.31]
 [ 9.36 12.6  14.04]
 [ 9.1  12.25 13.65]]
